/*
Descripcion: Realización de la tabla de Historial.
Nombre: Issacn David Puga Vazquez
Fecha: 26/06/2022.
 */
package Vista.Ventanas;

import Vista.Ventanas.Clientes.Clientes;
import java.awt.Color;
import javax.swing.JTable;
import Modelo.Conexion;
import Vista.Ventanas.Principal.Principal;
import java.awt.Color;
import java.awt.Container;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author issacpuga
 */
public class Historial extends javax.swing.JFrame {

    JTable Hist;
    ResultSet rs;
    Container cont = this.getContentPane();
       
    public Historial() {
        initComponents();
        cont.setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
        this.setTitle("Historial");
        
        
        DefaultTableModel dfm = new DefaultTableModel();
        Hist= this.tablaHistorial;
        Hist.setModel(dfm);
        
        dfm.setColumnIdentifiers(new Object[]{"ID","ALTURA","FECHA","PESO", "IDCLIENTE"});
        
        Conexion cn = new Conexion();
        rs = cn.SelectHistorial();
        try {
            while(rs.next()){
                dfm.addRow(new Object[]{rs.getInt("idHistorial"),rs.getFloat("altura"),rs.getDate("fecha"),rs.getFloat("peso"),rs.getInt("idCliente")});
            }
        } catch (Exception e) {
        }
        
        //initComponents();
        //getContentPane().setBackground(new Color(139,150,216));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnRegresarHistorial = new javax.swing.JButton();
        txtBuscarH = new javax.swing.JTextField();
        btnBuscarH = new javax.swing.JButton();
        btnNuevoH = new javax.swing.JButton();
        btnRefreshH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historial");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Ventanas/Icons/Imagen 3.png"))); // NOI18N

        btnRegresarHistorial.setBackground(new java.awt.Color(242, 242, 242));
        btnRegresarHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Ventanas/Icons/regreso (1).png"))); // NOI18N
        btnRegresarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarHistorialActionPerformed(evt);
            }
        });

        btnBuscarH.setBackground(new java.awt.Color(242, 242, 242));
        btnBuscarH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Ventanas/Icons/lupa.png"))); // NOI18N
        btnBuscarH.setAutoscrolls(true);
        btnBuscarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHActionPerformed(evt);
            }
        });

        btnNuevoH.setBackground(new java.awt.Color(242, 242, 242));
        btnNuevoH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Ventanas/Icons/nuevo.png"))); // NOI18N
        btnNuevoH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoHActionPerformed(evt);
            }
        });

        btnRefreshH.setBackground(new java.awt.Color(242, 242, 242));
        btnRefreshH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Ventanas/Icons/iconmonstr-synchronization-3-32.png"))); // NOI18N
        btnRefreshH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshHActionPerformed(evt);
            }
        });

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaHistorial);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Buscar:");

        jMenu1.setText("Propiedades");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnRegresarHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarH, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btnBuscarH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevoH)
                            .addComponent(btnRefreshH))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(btnBuscarH)
                    .addComponent(btnRegresarHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnNuevoH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefreshH)
                        .addGap(80, 80, 80))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarHistorialActionPerformed
        Clientes Client = new Clientes();
        Client.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarHistorialActionPerformed

    private void btnRefreshHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshHActionPerformed
        
        
        DefaultTableModel dfm = new DefaultTableModel();
        Hist= this.tablaHistorial;
        Hist.setModel(dfm);
        
        dfm.setColumnIdentifiers(new Object[]{"ID","ALTURA","FECHA","PESO", "IDCLIENTE"});
        
        Conexion cn = new Conexion();
        rs = cn.SelectHistorial();
        try {
            while(rs.next()){
                dfm.addRow(new Object[]{rs.getInt("idHistorial"),rs.getFloat("altura"),rs.getDate("fecha"),rs.getFloat("peso"),rs.getInt("idCliente")});
            }
        } catch (Exception e) {
        }
        
        
        
    }//GEN-LAST:event_btnRefreshHActionPerformed

    private void btnNuevoHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoHActionPerformed
        
        AgregarHistorial ah= new AgregarHistorial();
        ah.setVisible(true);
        //this.setVisible(false);
        //this.dispose();
                
    }//GEN-LAST:event_btnNuevoHActionPerformed

    private void btnBuscarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHActionPerformed
        
              
        DefaultTableModel dfm = new DefaultTableModel();
        String Nombre = (this.txtBuscarH.getText());
        
        
        Hist= this.tablaHistorial;
        Hist.setModel(dfm);
        
        dfm.setColumnIdentifiers(new Object[]{"ID","ALTURA","FECHA","PESO", "IDCLIENTE"});
        
        Conexion cn = new Conexion();
        rs = cn.BuscarHistorial(Nombre);
        try {
            while(rs.next()){
                dfm.addRow(new Object[]{rs.getInt("idHistorial"),rs.getFloat("altura"),rs.getDate("fecha"),rs.getFloat("peso"),rs.getInt("idCliente")});
            }
        } catch (Exception e) {
        }
       
        this.txtBuscarH.setText("");
        
        
        
        
    }//GEN-LAST:event_btnBuscarHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnBuscarH;
    javax.swing.JButton btnNuevoH;
    javax.swing.JButton btnRefreshH;
    javax.swing.JButton btnRegresarHistorial;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JMenu jMenu1;
    javax.swing.JMenuBar jMenuBar1;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTable tablaHistorial;
    javax.swing.JTextField txtBuscarH;
    // End of variables declaration//GEN-END:variables


}
